### ISSUE TITLE
Sometimes generate mac address functions returns multicast address

### ISSUE THREAD

**Issue by girikuncoro** [mahakamcloud/mahakam#24] opened 2018-12-27 08:06 UTC
Need to revisit https://github.com/mahakamcloud/mahakam/blob/master/pkg/network/mac_address.go to ensure only unicast address is generated.

**Comment by himani93** [comment] 2019-02-19 14:08
A address is called Unicast if least significant bit of an address's first octet is 0

In MAC address `FE:FE:53:61:52:1A`, the first octet is `FE` which in `1111 1110` in binary form. The least significant bit is already set to `0`. Therefore,  `FE:FE:53:61:52:1A` is a unicast MAC address.

As per the error, [`0xFE` is a reserved value in libvirt and cannot be used for a VMs MAC address. ](https://github.com/libvirt/libvirt/blob/600462834f4ec1955a9a48a1b6b4a390b9c31553/src/util/virnetdevtap.c#L624)

Libvirt reserves the MAC address starting with `0xFE` for tap devices.

Therefore, the MAC address to be generated should be unicast and should not start with `0xFE`.

**Comment by himani93** [comment] 2019-02-20 06:58
The issue is fixed in 5e7d1209bcb47aebd5dcf09467eac45c2a52da4a and test for the same are at 9e46a46e9fd4da7e7271de3eeb2267cfff5a8191

**Closed by himani93** 2019-02-20 06:58 UTC
Labels: kind/bug, needs more details
